// <auto-generated />
using ApiEmpresasProductos.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ApiEmpresasProductos.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ApiEmpresasProductos.Models.Empresa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumeroEmpleados")
                        .HasColumnType("int");

                    b.Property<int>("NumeroSucursales")
                        .HasColumnType("int");

                    b.Property<string>("Pais")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sector")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Empresas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "TechCorp",
                            NumeroEmpleados = 1000,
                            NumeroSucursales = 5,
                            Pais = "USA",
                            Sector = "Tecnología"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "AgroPlus",
                            NumeroEmpleados = 300,
                            NumeroSucursales = 2,
                            Pais = "Argentina",
                            Sector = "Agroindustria"
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "ConstruMax",
                            NumeroEmpleados = 450,
                            NumeroSucursales = 4,
                            Pais = "México",
                            Sector = "Construcción"
                        },
                        new
                        {
                            Id = 4,
                            Nombre = "MediSalud",
                            NumeroEmpleados = 500,
                            NumeroSucursales = 3,
                            Pais = "Colombia",
                            Sector = "Salud"
                        },
                        new
                        {
                            Id = 5,
                            Nombre = "EcoEnergy",
                            NumeroEmpleados = 150,
                            NumeroSucursales = 1,
                            Pais = "Chile",
                            Sector = "Energía"
                        });
                });

            modelBuilder.Entity("ApiEmpresasProductos.Models.Producto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Costo")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EmpresaId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId");

                    b.ToTable("Productos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Costo = 300m,
                            Descripcion = "Panel de alta eficiencia",
                            EmpresaId = 5,
                            Nombre = "Panel Solar"
                        },
                        new
                        {
                            Id = 2,
                            Costo = 1200m,
                            Descripcion = "ERP para empresas medianas",
                            EmpresaId = 1,
                            Nombre = "Software ERP"
                        },
                        new
                        {
                            Id = 3,
                            Costo = 8000m,
                            Descripcion = "Tractor con GPS",
                            EmpresaId = 2,
                            Nombre = "Tractor X200"
                        },
                        new
                        {
                            Id = 4,
                            Costo = 50m,
                            Descripcion = "Certificación internacional",
                            EmpresaId = 3,
                            Nombre = "Casco de seguridad"
                        },
                        new
                        {
                            Id = 5,
                            Costo = 3m,
                            Descripcion = "Fórmula pediátrica",
                            EmpresaId = 4,
                            Nombre = "Suero Oral"
                        },
                        new
                        {
                            Id = 6,
                            Costo = 400m,
                            Descripcion = "Andamio de aluminio",
                            EmpresaId = 3,
                            Nombre = "Andamio modular"
                        },
                        new
                        {
                            Id = 7,
                            Costo = 900m,
                            Descripcion = "CRM multiusuario",
                            EmpresaId = 1,
                            Nombre = "CRM Web"
                        },
                        new
                        {
                            Id = 8,
                            Costo = 10000m,
                            Descripcion = "Turbina de baja velocidad",
                            EmpresaId = 5,
                            Nombre = "Generador eólico"
                        },
                        new
                        {
                            Id = 9,
                            Costo = 2500m,
                            Descripcion = "Alta precisión",
                            EmpresaId = 2,
                            Nombre = "Pulverizador agrícola"
                        },
                        new
                        {
                            Id = 10,
                            Costo = 80m,
                            Descripcion = "Para uso clínico",
                            EmpresaId = 4,
                            Nombre = "Tensiómetro digital"
                        });
                });

            modelBuilder.Entity("ApiEmpresasProductos.Models.Producto", b =>
                {
                    b.HasOne("ApiEmpresasProductos.Models.Empresa", "Empresa")
                        .WithMany("Productos")
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("ApiEmpresasProductos.Models.Empresa", b =>
                {
                    b.Navigation("Productos");
                });
#pragma warning restore 612, 618
        }
    }
}
